//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alharamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class barbershop
    {
        public int barbershopID { get; set; }
        public string barbershopName { get; set; }
        public string barbershopLocation { get; set; }
        public string barbershopImg { get; set; }
    }
}
