//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace alharamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public int restaurantID { get; set; }
        public string restaurantName { get; set; }
        public string restaurantLocation { get; set; }
        public string restaurantImg { get; set; }
    }
}
